cuisines:
  ramen:
    title: "ラーメン"
    data_file: "data/2024_tokyo_ramen_restaurants_all_info.csv"
  sushi:
    title: "お寿司"
    data_file: "data/2024_tokyo_sushi_restaurants_all_info.csv"
  unagi:
    title: "うなぎ"
    data_file: "data/2024_tokyo_unagi_restaurants_all_info.csv"
  yakitori:
    title: "焼き鳥"
    data_file: "data/2024_tokyo_yakitori_restaurants_all_info.csv"
  tonkatsu:  
    title: "とんかつ"
    data_file: "data/2024_tokyo_tonkatsu_restaurants_all_info.csv"  